---
- name: Manage Cortensor Services
  hosts: "{{ target_hosts | default('all') }}"
  become: yes
  vars:
    action: "{{ service_action | default('status') }}"

  tasks:
    - name: Prepare key indices per host
      set_fact:
        key_indices: "{{ hostvars[inventory_hostname]['key_pair_index'] | string | replace(' ', '') | split(',') }}"
      when: hostvars[inventory_hostname]['key_pair_index'] is defined

    - name: Manage cortensor services
      systemd:
        name: "cortensor-{{ item }}"
        state: "{{ action }}"
        daemon_reload: "{{ 'yes' if action == 'reloaded' else 'no' }}"
      register: service_result
      when: action in ['started', 'stopped', 'restarted', 'reloaded']
      loop: "{{ key_indices }}"

    - name: Gather all service facts
      service_facts:
      when: action in ['started', 'stopped', 'restarted', 'reloaded']
      
    - name: Display service status
      debug:
        msg: |
          Node:  {{ inventory_hostname }}
          Instance: cortensor-{{ item }}
          Service:  {{ ansible_facts.services['cortensor-' ~ item ~ '.service'].state  | default('unknown') }}
          Enabled:  {{ ansible_facts.services['cortensor-' ~ item ~ '.service'].status | default('unknown') }}
      when: action in ['started', 'stopped', 'restarted', 'reloaded']
      loop: "{{ key_indices }}"
