---
- name: Register and Verify Cortensor Node
  hosts: all
  become: yes
  vars:
    cortensor_user: cortensor
    cortensor_home: "/home/{{ cortensor_user }}/.cortensor"
    cortensor_bin: "{{ cortensor_home }}/bin"

  tasks:
    - name: Prepare key indices per host
      set_fact:
        key_indices: "{{ hostvars[inventory_hostname]['key_pair_index'] | string | replace(' ', '') | split(',') }}"
      when: hostvars[inventory_hostname]['key_pair_index'] is defined

    - name: Run registration for each instance
      shell: "{{ cortensor_bin }}/cortensord register --env {{ cortensor_home }}/.env-{{ item }}"
      args:
        executable: /bin/bash
      become_user: "{{ cortensor_user }}"
      loop: "{{ key_indices }}"
      register: register_result
      ignore_errors: yes

    - name: Verify node for each instance
      shell: "{{ cortensor_bin }}/cortensord verify --env {{ cortensor_home }}/.env-{{ item }}"
      args:
        executable: /bin/bash
      become_user: "{{ cortensor_user }}"
      loop: "{{ key_indices }}"
      register: verify_result
      ignore_errors: yes

    - name: Display registration and verification results
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          Registration: {{ 'SUCCESS' if register_result is succeeded else 'FAILED' }}
          Verification: {{ 'SUCCESS' if verify_result is succeeded else 'FAILED' }}