---
- name: Ensure GPG and keyrings dir
  apt:
    name: gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Add Grafana repository
  ansible.builtin.shell: |
    echo "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list > /dev/null
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Grafana Alloy
  apt:
    name: alloy
    state: present

- name: Ensure Alloy config directory exists
  file:
    path: /etc/alloy
    state: directory
    mode: '0755'

- name: Render Alloy config
  template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
    mode: '0644'
  notify: reload alloy

- name: Enable and start alloy
  systemd:
    name: alloy
    enabled: yes
    state: restarted
